### ISSUE TITLE
Projects Page Giving TypeError

### ISSUE THREAD

**Issue by hadichaudhri** [DukeAML/Public-Website#65]
Visiting the Projects page results in a TypeError being raised—this is not noticeable in prod but blocks viewing the project page while in dev mode.

*Expected:* Project page reloads without error

*Actual:* Loading the page twice gives an "Unhandled Rejection (TypeError): undefined is not iterable (cannot read property Symbol(Symbol.iterator))" error message (see image below for how it looks in dev mode).

<img width="1113" alt="Project Page Error" src="https://user-images.githubusercontent.com/45558941/197276084-ac96e8ab-c8de-42fb-b248-3e7112e6e0ac.png">

**Comment by silva-nick** [comment]
I'll take this one. Looks like a problem with our CRM.

**Comment by silva-nick** [comment]
Should be resolved by b9b7ae5623fc588c67fdd8e34fe1a013ca51f51d.
